# Generated by Django 4.2 on 2023-07-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_profile_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='user',
        ),
    ]
